### ISSUE TITLE
LTS 8: Backend image editor crop settings are ignored

### ISSUE THREAD

**Issue by webrealisation** [alexanderschnitzler/fluid-styled-responsive-images#28] opened 2017-05-29 10:47 UTC
Hi.

I got the folloing behaviour:
Using the actual git-version with TYPO3 LTS 8.7.1 the image rendering process ignores the crop settings of the TYPO3 internal image editor. 
This happened directly after the installation of the extension - before Static Templates an TS Setup are added. Adding Templates and TS Setup does not change this behaviour.

If the extension is uninstalled image crop settings are respected again.

-------------------
Hint after testing:

TYPO3 8.7.1 generates defaultProcessConfiguration like this:

`Array ( [width] => 360m [crop] => {"default":{"cropArea":{"height":0.376,"width":0.503,"x":0.291,"y":0.6066666666666667},"selectedRatio":"16:9","focusArea":null}} )
`

TYPO3 7 LTS generates defaultProcessConfiguration like this - taken from a different project:

`Array ( [width] => 360m [crop] => {"x":1280,"y":960.3583426651736,"width":1280,"height":960.3429796355841,"rotate":0} )`

For testing i replaced the LTS 8 defaultProcessingConfiguration with the LTS 7 test confguration ind the Class Schnitzler\FluidStyledResponsiveImages\Resource\Rendering\Imagerenderer and it worked.
![image](https://cloud.githubusercontent.com/assets/16669096/26553696/14fe3bce-448d-11e7-9afc-cb4de5149bc5.png)

Hope this helps.

**Comment by ghost** [comment] 2017-08-01 10:08
Same error here.

Reason:
f:media doesn't support crop. When I use f:image the crop is work. But then the srcmaps not generated. 

Can u fix this asap?

**Comment by ghost** [comment] 2017-08-01 10:23
Bug solved. I make a pull request.

Currently it worked only for default cropped area.

**Comment by alexanderschnitzler** [comment] 2017-08-06 12:17
I used the PR but applied it manually in the TYPO3_8-7 branch. That's the branch I will use to generate 8.7 only versions.

See https://github.com/alexanderschnitzler/fluid-styled-responsive-images/commit/940a9661b781403389f9032d184b718b7993d08c

I will release a new version to TER soon. Also, I will close this ticket for now.
Feel free to reopen if you think the issue is not solved by the commit.

**Closed as completed by alexanderschnitzler** 2017-08-06 12:17 UTC
Labels: bug
