### ISSUE TITLE
f:media within Mask

### ISSUE THREAD

**Issue by ghost** [alexanderschnitzler/fluid-styled-responsive-images#26] opened 2017-03-06 09:10 UTC
Hello,

I think, I should open a new ticket for this problem.

When I use the f:media view helper within a mask element I don't get the sourceset attribute to my images.

Typoscript configuration:

```
tt_content {
    textmedia {
        settings {
            image_classes = {$styles.content.textmedia.imageClasses}
            responsive_image_rendering {
                layoutKey = srcset

                # Default Breakpoints
                sourceCollection {
                    xl {
                        width = 1200
                        srcset = 1200w
                    }

                    lg {
                        width = 992
                        srcset = 992w
                    }

                    md {
                        width = 768
                        srcset = 768w
                    }

                    sm {
                        width = 480
                        srcset = 480w
                    }

                    xs {
                        width = 320
                        srcset = 320w
                        sizes = auto
                    }
                }
            }

            origo < tx_origo
        }
    }
}

```

Within the Text & Media Element all work correct.

In my template I have the following loading order:

1. FSCI
2. Mask
3. My Extension who contains the mask layouts

I hope, u can help me.

**Comment by cedricziel** [comment] 2017-03-07 16:06
Can you please try to add a `dataKey` attribute to each of the source collections?

I could reproduce the error, but haven't found the root cause yet. Adding the dataKey attribute to each entry generates the appropriate attribute. I also added the information to the README

**Comment by ghost** [comment] 2017-03-08 08:20
I add ```dataKey``` to my typoscript configuration:

```
sourceCollection {
                    xl {
                        dataKey = extra-large
                        width = 1200
                        srcset = 1200w
                    }

                    lg {
                        data-key = large
                        width = 992
                        srcset = 992w
                    }

                    md {
                        data-key = medium
                        width = 768
                        srcset = 768w
                    }

                    sm {
                        data-key = small
                        width = 480
                        srcset = 480w
                    }

                    xs {
                        dataKey = extra-small
                        width = 320
                        srcset = 320w
                        sizes = auto
                    }
                }
```

But the output doesn't change:

```
<img src="fileadmin/origo/Placeholder/Images/6000x6000/sonstiges-03_6000x6000px.jpg" alt="Alt" title="Title" sizes="263px" class="media-object img-responsive lazyautosizes lazyloaded">
```

Before I test it, I clear all caches inclusive php op cache.

What is your extension loading order ? Do you have another idea ?

Greetings.

P.S:

f-media Tag:

```
<f:media class="media-object img-responsive lazyload" file="{data.tx_mask_contact_image.0}" alt="{data.tx_mask_contact_image.0.alternative}" title="{data.tx_mask_contact_image.0.title}"/>
```

**Comment by ghost** [comment] 2017-03-08 08:24
Hello,

please add the following to your documentation:

**When you use the f:media view helper the attribute "width" is necessary**

**Comment by ghost** [comment] 2017-03-08 08:27
Better solution: Can u add this to your renderer ?

**Comment by cedricziel** [comment] 2017-03-08 08:29
Sure, I can do that. Does that mean adding an explicit width fixes your problem?

**Comment by ghost** [comment] 2017-03-08 08:30
Yes. The better solution I think is the following:

Check if f:media has a width attribute. When yes use that. When no add as width the biggest width of source collection.

**Comment by ghost** [comment] 2017-03-08 08:39
Comment: The width needs to calculate. Width a fixed with of 1200px TYPO3 use the image width 1200px. But in a two columns grid I need only 700px. But he always use the 1200px image. 

I hope u found a solution for that.

**Comment by cedricziel** [comment] 2017-03-08 08:46
There is no way I would find a solution for that. - The problem: how would I? There is no reliable way to determine what would be needed to calculate that.

Since the original problem is fixed, I'm closing the ticket - feel free to open up another one if you miss anything or face problems :)

**Closed as completed by cedricziel** 2017-03-08 08:46 UTC
